export const mockWorkSessions = [
  {
    id: "pass01",
    date: "2026-01-14",
    startTime: "09:00",
    endTime: "11:00",
    title: "Bygga History logik",
    sessionType: "Deep Work",
    energyLevel: 4,
    category: "Utveckling",
  },
  {
    id: "pass02",
    date: "2026-01-14",
    startTime: "13:30",
    endTime: "15:00",
    title: "Boilerroom planering",
    sessionType: "Möte",
    energyLevel: 3,
    category: "Team",
  },
  {
    id: "pass03",
    date: "2026-01-13",
    startTime: "10:30",
    endTime: "12:00",
    title: "Fixa buggar i projekt",
    sessionType: "Deep Work",
    energyLevel: 5,
    category: "Utveckling",
  },
  {
    id: "pass04",
    date: "2026-01-12",
    startTime: "14:00",
    endTime: "14:15",
    title: "Paus och kaffe",
    sessionType: "Paus",
    energyLevel: 1,
    category: "Återhämtning",
  },
  {
    id: "pass05",
    date: "2026-01-12",
    startTime: "09:00",
    endTime: "11:15",
    title: "Gå igenom boilerroom projekt",
    sessionType: "Möte",
    energyLevel: 2,
    category: "Team",
  },
];
